version: '3'
services:
        ospredje:
                build:
                        context: ./ospredje
                        dockerfile: Dockerfile
                ports:
                        - 80:5000
                links:
                        - zaledje
                networks:
                        - delilnica-net

        zaledje:
                build:
                        context: ./zaledje
                        dockerfile: Dockerfile
                ports:
                        - 8000:8000
                volumes: 
                        - delilnica-baza:/delilnica/baza
                networks:
                        - delilnica-net

volumes:
        delilnica-baza:

networks:
        delilnica-net:
